package ru.pg13lac.nbanews.domain.entity.playerProfile

data class Average(
    val assists: Double,
    val blocked_att: Double,
    val blocks: Double,
    val def_rebounds: Double,
    val efficiency: Double,
    val fast_break_att: Double,
    val fast_break_made: Double,
    val fast_break_pts: Double,
    val field_goals_att: Double,
    val field_goals_made: Double,
    val flagrant_fouls: Double,
    val fouls_drawn: Double,
    val free_throws_att: Double,
    val free_throws_made: Double,
    val minutes: Double,
    val off_rebounds: Double,
    val offensive_fouls: Double,
    val personal_fouls: Double,
    val points: Double,
    val points_in_paint: Double,
    val points_in_paint_att: Double,
    val points_in_paint_made: Double,
    val points_off_turnovers: Double,
    val rebounds: Double,
    val second_chance_att: Double,
    val second_chance_made: Double,
    val second_chance_pts: Double,
    val steals: Double,
    val three_points_att: Double,
    val three_points_made: Double,
    val true_shooting_att: Double,
    val turnovers: Double,
    val two_points_att: Double,
    val two_points_made: Double
)