package ru.pg13lac.nbanews.domain.entity.testGameStatistic

data class Statistic(
    val assists: String,
    val biggestLead: String,
    val blocks: String,
    val defReb: String,
    val fastBreakPoints: String,
    val fga: String,
    val fgm: String,
    val fgp: String,
    val fta: String,
    val ftm: String,
    val ftp: String,
    val gameId: String,
    val longestRun: String,
    val min: String,
    val offReb: String,
    val pFouls: String,
    val plusMinus: String,
    val points: String,
    val pointsInPaint: String,
    val pointsOffTurnovers: String,
    val secondChancePoints: String,
    val steals: String,
    val teamId: String,
    val totReb: String,
    val tpa: String,
    val tpm: String,
    val tpp: String,
    val turnovers: String
)